#### MLP para clasificación

#### Se importan las librerias

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

# Libreria para el preprocesamiento de los datos
from sklearn import preprocessing
# Libreria sklearn para MLP
from sklearn.neural_network import MLPClassifier
# Se importa la libreria para dividir los datos de entrenamiento y de pruebas
from sklearn.model_selection import train_test_split
# Genera la matriz de confusión
from sklearn.metrics import confusion_matrix
# Gerera el reporte de la clasificación
from sklearn.metrics import classification_report
# Librerias para métricas del modelo
from sklearn.metrics import precision_score, recall_score, f1_score

#### Cargue de datos

In [2]:
data = pd.read_csv("Iris.csv")
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

#### Preprocesamiento

In [3]:
# Se convierten Species a valores numéricos para generar la clasificación
le = preprocessing.LabelEncoder()

# Se crea la columna wheather con los valores discretos
data['especie'] = le.fit_transform(data['Species'])

data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  especie  
0       Iris-setosa        0  
1       Iris-setosa        0  
2       Iris-setosa        0  
3       Iris-setosa        0  
4       Iris-setosa        0  
..              ...      ...  
145  Iris-virginica        2  
146  Iris-virginica        2  
147  Iris-virginica        2  
148  Iris-virginica        2  
149  Iris-virginica        2  

[150 rows x 7 columns]

#### Selección de característica y división de datos

In [4]:
# Se definen las características
features = ['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']
# calificación
X = data[features]
# se define la variable objetivo
y = data['especie'].values

# Se dividen los datos para el entrenamiento (80% entrenamiento y 20% pruebas)
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    train_size = 0.8, 
                                                    random_state= 1)

#### MLP

In [5]:
# Se crea el modelo
mlp = MLPClassifier()

# Se entrena el modelo
mlp.fit(X_train, y_train)

pred = mlp.predict(X_test)

# Se imprime la matriz de confusión
print(confusion_matrix(y_test, pred))
# Se imprime la precisión del modelo
print(classification_report(y_test, pred))

# Otras métricas clasificación: Precisión, Recall, F1-Score
print("Precisión: ", round(precision_score(y_test, pred, average='weighted'), 2))
print("Recall: ", round(recall_score(y_test, pred, average='weighted'),2))
print("F1-Score: ", round(f1_score(y_test, pred, average='weighted'),2))

[[11  0  0]
 [ 0 11  2]
 [ 0  0  6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.85      0.92        13
           2       0.75      1.00      0.86         6

    accuracy                           0.93        30
   macro avg       0.92      0.95      0.92        30
weighted avg       0.95      0.93      0.94        30

Precisión:  0.95
Recall:  0.93
F1-Score:  0.94


/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


#### Nueva predicción

In [6]:
# SepalLengthCm = 5.1
# SepalWidthCm = 3.5
# PetalLengthCm = 1.4
# PetalWidthCm = 0.2
# especie = 0 (Iris-setosa)

X_pred = [[5.1, 3.5, 1.4, 0.2]]


prediccion = mlp.predict(X_pred)

print("Especie :", prediccion)

Especie : [0]


/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(
